In [1]:
import tkinter as tk
from dragonfly import maximise_function, minimise_function
import socket
import struct
import numpy as np
import time
import re
import threading
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, NavigationToolbar2Tk)

#import classes from other files
import sys
sys.path.append("functions")
from functions_rest import GUI
#from functions_opt import OPT
from functions_hexapod import *
from functions_cam import *

udp_client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

C:\Users\loasis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dragonfly\utils\oper_utils.py:30: UserWarning: cannot import name 'direct' from 'dragonfly.utils.direct_fortran' (C:\Users\loasis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dragonfly\utils\direct_fortran\__init__.py)
Could not import Fortran direct library. Dragonfly can still be used, but might be slightly slower. To get rid of this warning, install a numpy compatible Fortran compiler (e.g. gfortran) and the python-dev package and reinstall Dragonfly.
  warn('%s\n%s'%(e, fortran_err_msg))


In [ ]:
root = tk.Tk()
my_gui = GUI(root)
root.mainloop()

[  65.5 1920.  1920.  1920. ]
[1924. 1932. 1932. 1924.]
[1928.   909.7  373.6  726.2]
[1920.   730.8 1920.  1920. ]
[1920.  1920.  1823.3  987.5]
[805.5 858.1 107.  214.5]


C:\Users\loasis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dragonfly\utils\oper_utils.py:132: UserWarning: Attempted to use direct, but fortran library could not be imported. Using PDOO optimiser instead of direct.
  warn(report_str)


[ 196. 1904. 1920. 1904.]
[ 490.3 1017.1  171.5   40.7]
[37.9 37.2 43.1 45.4]
[168.9 171.1 172.  608.7]
[342.1 343.8 351.2  39.2]
[ 66.7 157.8 153.  119.9]
[109.4  57.2  39.7  40.9]
[73.  74.2 42.9 40.3]
[ 38.5  39.4 261.3 314.9]
[188.9 232.6  85.2 110.9]
[  93.7   51.4 1904.  1900. ]
[1904.  1920.    48.9   50.3]
[  53.5  104.9  276.7 1137.8]
[878.1 802.  792.1  39.7]
[346.7 574.9 295.8 734.6]
[1155.7 1062.6  342.3   39.3]
[38.  40.9 26.8 25.3]
[ 97.8  92.2 666.8 729.1]
[204.5 150.8  48.4  89.1]
[163.6 216.8 245.1 243.4]
[229.  156.4 140.2 110.9]
[ 63.5  40.7 122.2 125.6]
[118.8 451.2 207.5  31.8]
[18.1 34.9 40.7  6.9]
[  12.7   95.9 1900.  1023.5]
[1900.  1164.7  421.7  191.9]
[125.6 130.4 962.6 972.1]
[272.9 258.   36.5  36.4]
[38.9 58.2 48.9 72.7]
[82.  87.6 84.9  8. ]
[ 8.9 25.4 22.5  7.3]
[ 120.8  140.4  715.1 1073.2]
[934.9 574.1  90.6  48.2]
[33.4 32.9 31.6 16.5]
[19.2 14.2 12.5  4.4]
[12.3 20.9 19.1 15.7]
[16.7 28.5 43.9 36.1]
[536.8 790.  785.3 927. ]
[495.6  90.2 555.4 504.4