In [1]:
import tkinter as tk
from dragonfly import maximise_function, minimise_function
import socket
import struct
import numpy as np
import time
import re
import threading
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, NavigationToolbar2Tk)

#import classes from other files
import sys
sys.path.append("functions")
from functions_rest import GUI
#from functions_opt import OPT
from functions_hexapod import *
from functions_cam import *

udp_client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

C:\Users\loasis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dragonfly\utils\oper_utils.py:30: UserWarning: cannot import name 'direct' from 'dragonfly.utils.direct_fortran' (C:\Users\loasis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dragonfly\utils\direct_fortran\__init__.py)
Could not import Fortran direct library. Dragonfly can still be used, but might be slightly slower. To get rid of this warning, install a numpy compatible Fortran compiler (e.g. gfortran) and the python-dev package and reinstall Dragonfly.
  warn('%s\n%s'%(e, fortran_err_msg))


In [ ]:
root = tk.Tk()
my_gui = GUI(root)
root.mainloop()

b'setypos>>-1.57'
b'setzpos>>-2.0'
b'setwangle>>-1.74'
b'setvangle>>-1.747'
[466. 466. 466. 466.]
[[-1.57  -2.077 -1.697 -1.834]
 [-1.57  -2.    -1.697 -1.834]
 [-1.57  -2.    -1.74  -1.834]
 [-1.57  -2.    -1.74  -1.747]]
b'setypos>>-1.831'
b'setzpos>>-2.178'
b'setwangle>>-1.81'
b'setvangle>>-1.906'
[466.  466.2 466.  466. ]
[[-1.831 -2.    -1.74  -1.747]
 [-1.831 -2.178 -1.74  -1.747]
 [-1.831 -2.178 -1.81  -1.747]
 [-1.831 -2.178 -1.81  -1.906]]
b'setypos>>-1.789'
b'setzpos>>-2.066'
b'setwangle>>-1.679'
b'setvangle>>-1.81'
[466. 466. 466. 466.]
[[-1.789 -2.178 -1.81  -1.906]
 [-1.789 -2.066 -1.81  -1.906]
 [-1.789 -2.066 -1.679 -1.906]
 [-1.789 -2.066 -1.679 -1.81 ]]
b'setypos>>-1.656'
b'setzpos>>-1.881'
b'setwangle>>-1.623'
b'setvangle>>-1.944'
[466. 466. 466. 466.]
[[-1.656 -2.066 -1.679 -1.81 ]
 [-1.656 -1.881 -1.679 -1.81 ]
 [-1.656 -1.881 -1.623 -1.81 ]
 [-1.656 -1.881 -1.623 -1.944]]
b'setypos>>-1.677'
b'setzpos>>-2.252'
b'setwangle>>-1.579'
b'setvangle>>-1.693'
[466. 466. 466